# Generated by Django 4.2.4 on 2023-09-10 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_category_options_alter_product_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColourVariant",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("colur_name", models.CharField(max_length=50)),
                ("price", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SizeVariant",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("size_name", models.CharField(max_length=50)),
                ("price", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="product",
            name="colour",
            field=models.ManyToManyField(to="products.colourvariant"),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(to="products.sizevariant"),
        ),
    ]
