# Generated by Django 4.2.4 on 2023-09-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_colourvariant_sizevariant_product_colour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="colour",
            field=models.ManyToManyField(blank=True, to="products.colourvariant"),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(blank=True, to="products.sizevariant"),
        ),
    ]
