# Generated by Django 4.2.4 on 2023-09-12 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_colour_alter_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="colour",
            field=models.ForeignKey(
                default="13b33fe7-5a31-4611-910c-3c209190dd26",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_colour",
                to="products.colourvariant",
            ),
            preserve_default=False,
        ),
    ]
