# Generated by Django 4.2.4 on 2023-09-12 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_productimage_colour"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("coupon_code", models.CharField(max_length=10)),
                ("is_expired", models.BooleanField(default=False)),
                ("discount", models.IntegerField(default=100)),
                ("min_price", models.IntegerField(default=500)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
